import OpenAI from 'openai';
import { GoogleGenAI } from '@google/genai';

// Initialize AI services
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

interface PlanData {
  type: string;
  userInfo: {
    name: string;
    goal: string;
    level: string;
    duration: string;
  };
  answers: any;
}

export async function generateComprehensivePlan(planData: PlanData): Promise<string> {
  const { type, userInfo, answers } = planData;
  
  try {
    // Use both AI services to create rich content
    const openaiContent = await generateOpenAIContent(type, userInfo, answers);
    const geminiContent = await generateGeminiContent(type, userInfo, answers);
    
    // Combine and format the content
    const combinedContent = await combineAndFormatContent(openaiContent, geminiContent, type, userInfo);
    
    return combinedContent;
    
  } catch (error) {
    console.error('AI content generation failed:', error);
    // Fallback to comprehensive static content
    return generateFallbackContent(type, userInfo);
  }
}

async function generateOpenAIContent(type: string, userInfo: any, answers: any): Promise<any> {
  const prompt = `Create a comprehensive ${type} plan for ${userInfo.name}. Their goal is: ${userInfo.goal}. Experience level: ${userInfo.level}. Duration: ${userInfo.duration}.

Create detailed content including:
1. Personalized recommendations
2. Weekly schedules
3. Daily tracking sheets
4. Progress milestones
5. Tips and motivation

Return as JSON with sections: overview, weekly_plan, daily_tracking, tips, milestones`;

  const response = await openai.chat.completions.create({
    model: "gpt-4o", // the newest OpenAI model is "gpt-5" which was released August 7, 2025. do not change this unless explicitly requested by the user
    messages: [
      {
        role: "system",
        content: "You are an expert health and wellness coach. Create detailed, actionable plans."
      },
      {
        role: "user",
        content: prompt
      }
    ],
    response_format: { type: "json_object" },
    max_tokens: 4000
  });

  try {
    return JSON.parse(response.choices[0].message.content || '{}');
  } catch {
    return { overview: "Personalized plan generated by AI", weekly_plan: [], daily_tracking: [], tips: [], milestones: [] };
  }
}

async function generateGeminiContent(type: string, userInfo: any, answers: any): Promise<any> {
  const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
  
  const prompt = `Generate additional ${type} content for ${userInfo.name}:
- Shopping lists or equipment needs
- Meal recipes or exercise variations
- Troubleshooting guides
- Success strategies
- Weekly reflection prompts

Format as JSON with: shopping_list, recipes_exercises, troubleshooting, strategies, reflections`;

  const result = await model.generateContent({
    contents: prompt,
    generationConfig: {
      responseMimeType: "application/json"
    }
  });

  try {
    const content = result.response.text();
    return JSON.parse(content);
  } catch {
    return { shopping_list: [], recipes_exercises: [], troubleshooting: [], strategies: [], reflections: [] };
  }
}

async function combineAndFormatContent(openaiContent: any, geminiContent: any, type: string, userInfo: any): Promise<string> {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Your ${type.charAt(0).toUpperCase() + type.slice(1)} Plan</title>
  <style>
    @page { size: A4; margin: 20px; }
    * { box-sizing: border-box; }
    body { 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
      line-height: 1.6; 
      color: #333; 
      margin: 0; 
      padding: 0;
    }
    .header { 
      background: linear-gradient(135deg, #16a34a, #059669); 
      color: white; 
      padding: 30px; 
      text-align: center; 
      border-radius: 10px; 
      margin-bottom: 30px;
    }
    .header h1 { margin: 0; font-size: 32px; font-weight: bold; }
    .header p { margin: 10px 0 0 0; font-size: 16px; opacity: 0.9; }
    .page-break { page-break-before: always; }
    .section { margin-bottom: 30px; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px; }
    .section h2 { 
      color: #16a34a; 
      border-bottom: 3px solid #16a34a; 
      padding-bottom: 10px; 
      margin-bottom: 20px;
      font-size: 24px;
    }
    .section h3 { color: #059669; margin-top: 25px; font-size: 18px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin: 20px 0; }
    .card { 
      border: 1px solid #d1d5db; 
      border-radius: 8px; 
      padding: 20px; 
      background: #f9fafb;
    }
    .card h4 { margin: 0 0 15px 0; color: #16a34a; font-size: 16px; }
    table { 
      width: 100%; 
      border-collapse: collapse; 
      margin: 20px 0; 
      background: white;
    }
    th, td { 
      border: 1px solid #d1d5db; 
      padding: 12px; 
      text-align: left; 
    }
    th { 
      background: #16a34a; 
      color: white; 
      font-weight: bold;
    }
    tr:nth-child(even) { background: #f9fafb; }
    ul, ol { padding-left: 20px; }
    li { margin: 8px 0; }
    .highlight { 
      background: #fef3c7; 
      border-left: 4px solid #f59e0b; 
      padding: 15px; 
      margin: 20px 0;
      border-radius: 4px;
    }
    .tracker { 
      display: grid; 
      grid-template-columns: repeat(8, 1fr); 
      gap: 10px; 
      margin: 20px 0;
    }
    .tracker-item { 
      border: 1px solid #d1d5db; 
      padding: 10px; 
      text-align: center; 
      border-radius: 4px;
    }
    .footer { 
      margin-top: 40px; 
      padding: 20px; 
      background: #f3f4f6; 
      text-align: center; 
      font-size: 12px; 
      color: #6b7280;
      border-radius: 8px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Your Personalized ${type.charAt(0).toUpperCase() + type.slice(1)} Plan</h1>
    <p>Created for ${userInfo.name} • Goal: ${userInfo.goal} • Level: ${userInfo.level} • Duration: ${userInfo.duration}</p>
    <p>Generated on ${new Date().toLocaleDateString()} • PlantRx App</p>
  </div>

  <!-- Page 1: Overview & Introduction -->
  <div class="section">
    <h2>Welcome to Your Journey</h2>
    <div class="highlight">
      <h3>Your Personal Plan Overview</h3>
      <p>${openaiContent.overview || `This comprehensive ${type} plan has been specifically designed for you based on your goals and experience level. Follow this guide for the next ${userInfo.duration} to achieve your health and wellness objectives.`}</p>
    </div>
    
    <h3>What You'll Achieve</h3>
    <div class="grid">
      ${(openaiContent.milestones || [
        "Improved daily habits and routines",
        "Better understanding of your body's needs", 
        "Sustainable lifestyle changes",
        "Increased energy and vitality"
      ]).map((milestone: string) => `
        <div class="card">
          <h4>✓ ${milestone}</h4>
        </div>
      `).join('')}
    </div>
  </div>

  <div class="page-break"></div>

  <!-- Page 2: Weekly Schedule -->
  <div class="section">
    <h2>Your ${userInfo.duration} Schedule</h2>
    
    ${generateWeeklySchedule(type, openaiContent.weekly_plan)}
    
    <h3>Daily Structure</h3>
    <table>
      <thead>
        <tr><th>Time</th><th>Activity</th><th>Duration</th><th>Notes</th></tr>
      </thead>
      <tbody>
        <tr><td>Morning</td><td>Primary ${type} activity</td><td>30-45 min</td><td>Best energy time</td></tr>
        <tr><td>Midday</td><td>Progress check-in</td><td>5-10 min</td><td>Track & adjust</td></tr>
        <tr><td>Evening</td><td>Reflection & planning</td><td>10-15 min</td><td>Prepare for tomorrow</td></tr>
      </tbody>
    </table>
  </div>

  <div class="page-break"></div>

  <!-- Page 3: Daily Tracking & Tools -->
  <div class="section">
    <h2>Daily Tracking Tools</h2>
    
    <h3>Weekly Progress Tracker</h3>
    <table>
      <thead>
        <tr>
          <th>Day</th>
          <th>Completed</th>
          <th>Energy (1-10)</th>
          <th>Motivation (1-10)</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        ${['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(day => `
          <tr>
            <td>${day}</td>
            <td>☐</td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <h3>Habit Tracker</h3>
    <div class="tracker">
      ${(openaiContent.daily_tracking || [
        "Morning routine", "Main activity", "Water intake", "Nutrition goals",
        "Movement", "Mindfulness", "Sleep prep", "Reflection"
      ]).map((habit: string) => `
        <div class="tracker-item">
          <strong>${habit}</strong><br>
          ☐ ☐ ☐ ☐ ☐ ☐ ☐
        </div>
      `).join('')}
    </div>
  </div>

  <div class="page-break"></div>

  <!-- Page 4: Resources & Guidelines -->
  <div class="section">
    <h2>Essential Resources</h2>
    
    ${generateResourceSection(type, geminiContent)}
    
    <h3>Success Tips</h3>
    <ul>
      ${(openaiContent.tips || [
        "Start small and build consistency",
        "Track your progress daily",
        "Celebrate small wins",
        "Adjust the plan as needed",
        "Stay patient with the process"
      ]).map((tip: string) => `<li>${tip}</li>`).join('')}
    </ul>

    <div class="highlight">
      <h3>Troubleshooting Common Challenges</h3>
      ${(geminiContent.troubleshooting || [
        "Low motivation: Review your 'why' and start with easier tasks",
        "Time constraints: Break activities into smaller 10-15 minute segments",
        "Plateau: Gradually increase intensity or try variations"
      ]).map((item: string) => `<p><strong>•</strong> ${item}</p>`).join('')}
    </div>
  </div>

  <div class="page-break"></div>

  <!-- Page 5: Reflection & Progress -->
  <div class="section">
    <h2>Weekly Reflection & Planning</h2>
    
    <h3>Week 1 Reflection</h3>
    <table>
      <thead>
        <tr><th>Question</th><th>Your Response</th></tr>
      </thead>
      <tbody>
        <tr><td>What went well this week?</td><td style="height: 60px;"></td></tr>
        <tr><td>What was challenging?</td><td style="height: 60px;"></td></tr>
        <tr><td>What will you adjust next week?</td><td style="height: 60px;"></td></tr>
        <tr><td>Rate your overall progress (1-10)</td><td style="height: 60px;"></td></tr>
      </tbody>
    </table>

    <h3>Monthly Progress Review</h3>
    <div class="grid">
      <div class="card">
        <h4>Achievements</h4>
        <p>List 3 major accomplishments:</p>
        <ol>
          <li style="height: 30px;"></li>
          <li style="height: 30px;"></li>
          <li style="height: 30px;"></li>
        </ol>
      </div>
      <div class="card">
        <h4>Lessons Learned</h4>
        <p>Key insights about yourself:</p>
        <ol>
          <li style="height: 30px;"></li>
          <li style="height: 30px;"></li>
          <li style="height: 30px;"></li>
        </ol>
      </div>
    </div>

    <h3>Next Phase Planning</h3>
    ${(geminiContent.reflections || [
      "What aspects of this plan will you continue?",
      "What new challenges are you ready to take on?",
      "How will you maintain your progress long-term?"
    ]).map((question: string) => `
      <div style="margin: 20px 0; border: 1px dashed #d1d5db; padding: 15px; border-radius: 4px;">
        <strong>${question}</strong>
        <div style="height: 60px; margin-top: 10px;"></div>
      </div>
    `).join('')}
  </div>

  <div class="footer">
    <p><strong>PlantRx App</strong> • Your Personalized Health Journey</p>
    <p>This plan is for educational purposes only. Consult healthcare professionals for medical advice.</p>
    <p>Visit plantrxapp.com for more resources and support</p>
  </div>
</body>
</html>`;

  return html;
}

function generateWeeklySchedule(type: string, weeklyPlan: any[]): string {
  const schedules = {
    diet: [
      { week: 1, focus: "Foundation Building", activities: ["Meal prep basics", "Hydration tracking", "Portion awareness"] },
      { week: 2, focus: "Nutrient Optimization", activities: ["Balanced macros", "Micronutrient focus", "Timing strategies"] },
      { week: 3, focus: "Advanced Planning", activities: ["Recipe mastery", "Social eating", "Adaptation skills"] },
      { week: 4, focus: "Lifestyle Integration", activities: ["Long-term habits", "Maintenance planning", "Goal reassessment"] }
    ],
    fitness: [
      { week: 1, focus: "Movement Foundation", activities: ["Form mastery", "Consistency building", "Recovery practices"] },
      { week: 2, focus: "Strength Building", activities: ["Progressive overload", "Core stability", "Flexibility work"] },
      { week: 3, focus: "Performance Phase", activities: ["Intensity training", "Skill development", "Endurance building"] },
      { week: 4, focus: "Peak & Maintenance", activities: ["Peak performance", "Program evaluation", "Future planning"] }
    ],
    wellness: [
      { week: 1, focus: "Mindfulness Foundation", activities: ["Daily meditation", "Stress awareness", "Sleep optimization"] },
      { week: 2, focus: "Emotional Balance", activities: ["Mood tracking", "Gratitude practice", "Boundary setting"] },
      { week: 3, focus: "Energy Management", activities: ["Time blocking", "Priority setting", "Energy optimization"] },
      { week: 4, focus: "Holistic Integration", activities: ["Life balance", "Sustainable practices", "Growth planning"] }
    ]
  };

  const defaultSchedule = schedules.diet;
  const schedule = schedules[type as keyof typeof schedules] || defaultSchedule;

  return `
    <table>
      <thead>
        <tr><th>Week</th><th>Focus</th><th>Key Activities</th></tr>
      </thead>
      <tbody>
        ${schedule.map(week => `
          <tr>
            <td><strong>Week ${week.week}</strong></td>
            <td>${week.focus}</td>
            <td>${week.activities.join(' • ')}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
}

function generateResourceSection(type: string, geminiContent: any): string {
  const resources = {
    diet: {
      title: "Nutrition Resources",
      items: geminiContent.shopping_list || [
        "Lean proteins (chicken, fish, tofu)",
        "Complex carbohydrates (quinoa, sweet potatoes)",
        "Healthy fats (avocado, nuts, olive oil)",
        "Fresh fruits and vegetables",
        "Herbs and spices for flavor"
      ]
    },
    fitness: {
      title: "Equipment & Exercises",
      items: geminiContent.recipes_exercises || [
        "Bodyweight exercises (push-ups, squats)",
        "Resistance bands for strength training",
        "Yoga mat for stretching",
        "Water bottle for hydration",
        "Comfortable workout clothes"
      ]
    },
    wellness: {
      title: "Wellness Tools",
      items: geminiContent.strategies || [
        "Meditation app or guided sessions",
        "Journal for reflection",
        "Essential oils for relaxation",
        "Comfortable space for practice",
        "Timer for mindfulness exercises"
      ]
    }
  };

  const defaultResource = resources.diet;
  const resource = resources[type as keyof typeof resources] || defaultResource;

  return `
    <h3>${resource.title}</h3>
    <div class="grid">
      ${resource.items.map((item: string) => `
        <div class="card">
          <h4>• ${item}</h4>
        </div>
      `).join('')}
    </div>
  `;
}

function generateFallbackContent(type: string, userInfo: any): string {
  // Comprehensive fallback with 5+ pages of content
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Your ${type.charAt(0).toUpperCase() + type.slice(1)} Plan</title>
  <style>
    @page { size: A4; margin: 20px; }
    body { font-family: Arial, sans-serif; line-height: 1.6; }
    .header { background: #16a34a; color: white; padding: 20px; text-align: center; margin-bottom: 20px; }
    .page-break { page-break-before: always; }
    .section { margin-bottom: 30px; }
    h2 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; }
    th { background: #f5f5f5; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Your Comprehensive ${type.charAt(0).toUpperCase() + type.slice(1)} Plan</h1>
    <p>Personalized for ${userInfo.name} • ${userInfo.duration}</p>
  </div>

  <div class="section">
    <h2>Page 1: Your Personal Journey</h2>
    <p>Welcome ${userInfo.name}! This ${type} plan is designed specifically for your goal: ${userInfo.goal}</p>
    <p>Experience Level: ${userInfo.level} | Duration: ${userInfo.duration}</p>
  </div>

  <div class="page-break"></div>
  
  <div class="section">
    <h2>Page 2: Weekly Schedule</h2>
    <table>
      <tr><th>Week</th><th>Focus</th><th>Activities</th></tr>
      <tr><td>1</td><td>Foundation</td><td>Building basic habits and routines</td></tr>
      <tr><td>2</td><td>Development</td><td>Progressing and refining techniques</td></tr>
      <tr><td>3</td><td>Optimization</td><td>Fine-tuning and maximizing results</td></tr>
      <tr><td>4</td><td>Mastery</td><td>Achieving goals and planning ahead</td></tr>
    </table>
  </div>

  <div class="page-break"></div>
  
  <div class="section">
    <h2>Page 3: Daily Tracking</h2>
    <table>
      <tr><th>Day</th><th>Morning</th><th>Afternoon</th><th>Evening</th><th>Progress</th></tr>
      ${Array.from({length: 7}, (_, i) => `
        <tr><td>Day ${i+1}</td><td>☐</td><td>☐</td><td>☐</td><td></td></tr>
      `).join('')}
    </table>
  </div>

  <div class="page-break"></div>
  
  <div class="section">
    <h2>Page 4: Resources & Guidelines</h2>
    <h3>Essential Tips</h3>
    <ul>
      <li>Stay consistent with daily practices</li>
      <li>Track your progress regularly</li>
      <li>Adjust the plan based on your needs</li>
      <li>Celebrate small victories</li>
      <li>Be patient with the process</li>
    </ul>
  </div>

  <div class="page-break"></div>
  
  <div class="section">
    <h2>Page 5: Progress Review</h2>
    <h3>Weekly Reflection Questions</h3>
    <p><strong>What went well this week?</strong></p>
    <div style="height: 50px; border: 1px solid #ddd; margin: 10px 0;"></div>
    <p><strong>What challenges did you face?</strong></p>
    <div style="height: 50px; border: 1px solid #ddd; margin: 10px 0;"></div>
    <p><strong>What will you focus on next week?</strong></p>
    <div style="height: 50px; border: 1px solid #ddd; margin: 10px 0;"></div>
  </div>

  <div style="margin-top: 40px; text-align: center; font-size: 12px;">
    <p>PlantRx App • Your Health Journey Partner</p>
  </div>
</body>
</html>`;
}