// pdf-maker.js
// Usage: node pdf-maker.js template.html out.pdf
import fs from "fs/promises";
import puppeteer from "puppeteer";

const [,, inFile, outFile = "out.pdf"] = process.argv;
if (!inFile) {
  console.error("Usage: node pdf-maker.js template.html out.pdf");
  process.exit(1);
}

const html = await fs.readFile(inFile, "utf8");

const browser = await puppeteer.launch({
  headless: true,
  args: ["--no-sandbox", "--disable-setuid-sandbox"]
});

const page = await browser.newPage();

// Helpful logs from the page (catch layout/asset errors)
page.on("console", msg => console.log("[page]", msg.text()));
page.on("pageerror", err => console.error("[pageerror]", err.message));

// Set content & use print media rules
await page.setContent(html, { waitUntil: ["domcontentloaded"] });
await page.emulateMediaType("print");

// Wait for fonts & late images
try { await page.evaluateHandle("document.fonts.ready"); } catch {}
await page.waitForNetworkIdle({ idleTime: 800, timeout: 15000 }).catch(()=>{});

// Header/Footer templates
const headerTemplate = `
<style>
  .head { font-size:9px; width:100%; padding:0 10mm; }
  .left { float:left } .right { float:right }
</style>
<div class="head">
  <span class="left">PlantRx Fitness Routines</span>
  <span class="right"><span class="date"></span></span>
</div>
<script>
  document.querySelector('.date').textContent =
    new Date().toISOString().slice(0,10);
</script>
`;

const footerTemplate = `
<style>
  .foot { font-size:9px; width:100%; padding:0 10mm; }
  .right { float:right }
</style>
<div class="foot">
  <span>Generated by PlantRx</span>
  <span class="right">Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
</div>
`;

await page.pdf({
  path: outFile,
  format: "A4",
  printBackground: true,
  preferCSSPageSize: true,
  displayHeaderFooter: true,
  headerTemplate,
  footerTemplate,
  margin: { top: "18mm", right: "12mm", bottom: "22mm", left: "12mm" }
});

await browser.close();
console.log("Saved", outFile);