export const ARTICLE_IMAGE_MAP: Record<string, string> = {
  "natural-hormonal-acne-treatment-plants": "/attached_assets/remedy_images/Acne%20Fighting%20Face%20Mask.jpg",
  "natural-constipation-remedies-that-work": "/attached_assets/remedy_images/Digestive%20Harmony%20Herbal%20Tea.jpg",
  "turmeric-vs-ibuprofen-inflammation": "/attached_assets/remedy_images/Golden%20Turmeric%20Inflammation%20Fighter.jpg",
  "glp1-agonists-vs-natural-weight-loss-plant-alternatives": "/attached_assets/remedy_images/Metabolism%20Booster.jpg",
  "longevity-secrets-blue-zones-plants-add-years-life": "/attached_assets/remedy_images/Natural%20Longevity%20Complex.jpg",
  "ai-powered-personalized-nutrition-future-plant-medicine": "/attached_assets/remedy_images/brain-boosting-herbal-tea.jpg",
  "cold-therapy-revolution-ice-baths-cryotherapy-natural-exposure": "/attached_assets/remedy_images/Cold%20%26%20Heat%20Protocol.jpg",
  "10-powerful-natural-remedies-science-backed": "/attached_assets/remedy_images/Traditional%20Echinacea%20Immune%20Support%20Tincture.jpg",
  "complete-guide-home-herbal-medicine-cabinet": "/attached_assets/remedy_images/Stress%20Relief%20Herbal%20Tea.jpg",
  "adaptogens-explained-stress-fighting-superherbs": "/attached_assets/remedy_images/rhodiola-stress-shield-complex.jpg",
  "detox-body-naturally-plants-liver-health": "/attached_assets/remedy_images/Cleansing%20Dandelion%20Root%20Liver%20Detox%20Tea.jpg",
  "plant-based-remedies-better-sleep-natural-insomnia-solutions": "/attached_assets/remedy_images/Peaceful%20Valerian%20Root%20Sleep%20Enhancement%20Tea.jpg",
  "natural-anxiety-remedies-no-side-effects": "/attached_assets/remedy_images/Calming%20Passionflower%20Relief%20Tincture.jpg",
  "natural-immune-system-boosters-herbs": "/attached_assets/remedy_images/Immune%20Defense%20Formula.jpg",
  "ai-vs-doctors-health-diagnosis-accuracy": "/attached_assets/remedy_images/Brain%20Power%20Mushroom.jpg",
  "natural-remedies-chronic-fatigue": "/attached_assets/remedy_images/Cellular%20Energy%20Boost.jpg",
  "complete-guide-anti-inflammatory-eating": "/attached_assets/remedy_images/Anti-Inflammatory%20Ginger%20Turmeric%20Tea.jpg",
  "plant-protein-complete-guide-vegan-muscle": "/attached_assets/remedy_images/Athletic%20Performance%20Boost.jpg",
  "gut-health-prebiotics-probiotics-explained": "/attached_assets/remedy_images/Gut%20Lining%20body.jpg",
  "intermittent-fasting-benefits-science-guide": "/attached_assets/remedy_images/Gentle%20Cleanse%20Formula.jpg",
  "vitamin-d-optimization-sunshine-vitamin-guide": "/attached_assets/remedy_images/Energizing%20Green%20Tea%20Antioxidant%20Blend.jpg",
  "omega-3-omega-6-balancing-fatty-acids": "/attached_assets/remedy_images/Heart%20Circulation%20Support.jpg",
  "blood-sugar-balance-natural-glucose-control": "/attached_assets/remedy_images/Blood%20Sugar%20Support.jpg",
  "magnesium-deficiency-silent-epidemic": "/attached_assets/remedy_images/Electrolyte-Rich%20Cramp%20Prevention%20Formula.jpg",
  "liver-detox-foods-natural-support": "/attached_assets/remedy_images/Regenerating%20Schisandra%20Berry%20Liver%20Tonic.jpg",
  "iron-rich-foods-preventing-anemia-naturally": "/attached_assets/remedy_images/Blood%20Purifier.jpg",
  "electrolyte-balance-hydration-beyond-water": "/attached_assets/remedy_images/Hydration%20%26%20Electrolyte%20Rebalance.jpg",
  "collagen-joint-skin-health-complete-guide": "/attached_assets/remedy_images/Skin%20Regeneration%20Oil.jpg",
  "adaptogenic-herbs-natures-stress-solutions": "/attached_assets/remedy_images/Calming%20Lavender%20Stress%20Relief%20Balm.jpg",
  "elderberry-immune-support-research-recipes": "/attached_assets/remedy_images/Immune-Shield%20Echinacea%20Throat%20Support.jpg",
  "milk-thistle-liver-best-friend": "/attached_assets/remedy_images/Detoxing%20Juniper%20Berry%20Kidney%20Tincture.jpg",
  "valerian-root-melatonin-sleep-solutions-compared": "/attached_assets/remedy_images/California%20Poppy%20Sleep%20Tincture.jpg",
  "echinacea-immune-booster-myth": "/attached_assets/remedy_images/Echinacea.jpg",
  "ginger-digestive-anti-nausea-remedy": "/attached_assets/remedy_images/Fresh%20Ginger%20Nausea%20Tea.jpg",
  "chamomile-more-than-bedtime-tea": "/attached_assets/remedy_images/Bedtime%20Chamomile%20Honey%20Sleep%20Tea.jpg",
  "peppermint-natural-relief-ibs-headaches": "/attached_assets/remedy_images/Simple%20Peppermint%20Tea%20Digestive%20Aid.jpg",
  "st-johns-wort-natural-antidepressant-alternative": "/attached_assets/remedy_images/Mucuna%20Pruriens%20Mood%20Support.jpg",
  "lavender-aromatherapy-clinical-evidence": "/attached_assets/remedy_images/Calming%20Lavender%20Honey%20Sleep%20Aid.jpg",
  "saw-palmetto-prostate-health-men": "/attached_assets/remedy_images/Prostate%20Support%20Formula.jpg",
  "oregano-oil-natures-powerful-antimicrobial": "/attached_assets/remedy_images/Natural%20Garlic%20Antimicrobial%20Defense.jpg",
  "grounding-science-earthing-health": "/attached_assets/remedy_images/Relaxing%20Epsom%20Salt%20Foot%20Soak.jpg",
  "breathwork-techniques-stress-anxiety": "/attached_assets/remedy_images/Deep%20Breathing%20Stress-Release%20Method.jpg",
  "cold-exposure-therapy-benefits-cold-showers-ice-baths": "/attached_assets/remedy_images/Cold%20%26%20Flu%20Fighter.jpg",
  "forest-bathing-japanese-practice-shinrin-yoku": "/attached_assets/remedy_images/Energizing%20Green%20Tea%20Morning%20Boost.jpg",
  "digital-detox-reclaiming-mental-space": "/attached_assets/remedy_images/Brain%20Circulation%20Booster.jpg",
  "morning-routines-healthy-successful-people": "/attached_assets/remedy_images/Morning%20Energy%20Herbal%20Blend.jpg",
  "sleep-hygiene-perfect-sleep-environment": "/attached_assets/remedy_images/Reishi%20Mushroom%20Deep%20Sleep%20Formula.jpg",
  "journaling-mental-health-science-backed-benefits": "/attached_assets/remedy_images/Stress-Relief%20Deep%20Breathing%20Exercise.jpg",
  "healing-power-laughter-science-joy": "/attached_assets/remedy_images/Kanna%20Stress%20Relief%20Tincture.jpg",
  "sauna-therapy-heat-exposure-longevity": "/attached_assets/remedy_images/Warming%20Turmeric%20Golden%20Milk.jpg",
  "mindful-eating-transform-relationship-food": "/attached_assets/remedy_images/Digestive%20Enzyme.jpg",
  "sound-healing-frequencies-health-relaxation": "/attached_assets/remedy_images/Relaxing%20Lavender%20Chamomile%20Tension%20Blend.jpg",
  "mobility-vs-flexibility-body-needs": "/attached_assets/remedy_images/Joint%20Support%20Formula.jpg",
  "zone-2-training-endurance-fat-burning": "/attached_assets/remedy_images/Siberian%20Strength%20Boost.jpg",
  "strength-training-beginners-complete-guide": "/attached_assets/remedy_images/Male%20Vitality%20Support.jpg",
  "recovery-science-optimize-rest-better-results": "/attached_assets/remedy_images/Healing%20Recovery%20Gel.jpg",
  "hiit-vs-steady-state-cardio-best": "/attached_assets/remedy_images/Circulation%20Enhancer.jpg",
  "natural-ways-boost-testosterone-hormonal-health": "/attached_assets/remedy_images/Mens%20Vitality%20Herbal%20Blend.jpg",
  "walking-underrated-exercise-longevity": "/attached_assets/remedy_images/Natural%20Energy%20Tea.jpg",
  "yoga-athletes-performance-prevent-injury": "/attached_assets/remedy_images/Neck%20%26%20Shoulder%20Stretches.jpg",
  "building-home-gym-any-budget": "/attached_assets/remedy_images/Male%20Enhancement%20Formula.jpg",
  "core-training-beyond-crunches-functional-strength": "/attached_assets/remedy_images/Black%20Maca%20Vitality.jpg",
  "natural-pre-workout-alternatives-supplements": "/attached_assets/remedy_images/Energizing%20Panax%20Ginseng%20Brain%20Tea.jpg",
  "swimming-perfect-low-impact-full-body-workout": "/attached_assets/remedy_images/Healing%20Digestive%20Juice.jpg",
  "power-berries-antioxidant-superfoods": "/attached_assets/remedy_images/Antioxidant%20Immune%20Tea.jpg",
  "cruciferous-vegetables-cancer-fighting-nutrition": "/attached_assets/remedy_images/Cellular%20Cleanup%20Formula.jpg",
  "fermented-foods-ancient-wisdom-gut-health": "/attached_assets/remedy_images/Digestive%20Support%20Formula.jpg",
  "nuts-seeds-small-packages-big-nutrition": "/attached_assets/remedy_images/Amazon%20Energy%20Seeds.jpg",
  "leafy-greens-foundation-healthy-diet": "/attached_assets/remedy_images/Green%20Superfood%20Powder.jpg",
  "bone-broth-ancient-elixir-modern-health": "/attached_assets/remedy_images/Ginger%20Support%20Formula.jpg",
  "avocados-perfect-healthy-fat": "/attached_assets/remedy_images/Skin%20Hydration%20Complex.jpg",
  "wild-caught-vs-farm-raised-fish-healthiest": "/attached_assets/remedy_images/Five-Flavor%20Energy%20Berry.jpg",
  "garlic-onions-allium-vegetables-immunity": "/attached_assets/remedy_images/Garlic%20Immune%20Booster.jpg",
  "legumes-plant-protein-fiber-powerhouses": "/attached_assets/remedy_images/Peruvian%20Power%20Root.jpg",
  "eggs-natures-perfect-protein-package": "/attached_assets/remedy_images/Morning%20Detox%20Drink.jpg",
  "olive-oil-liquid-gold-mediterranean": "/attached_assets/remedy_images/Natural%20Olive%20Oil%20Hair%20Mask.jpg",
  "natural-anxiety-relief-evidence-based-approaches": "/attached_assets/remedy_images/wood-betony-anxiety-relief-tea.jpg",
  "depression-inflammation-mind-body-connection": "/attached_assets/remedy_images/Inflammation%20Fighter.jpg",
  "mindfulness-meditation-beginners-complete-guide": "/attached_assets/remedy_images/Jatamansi%20Calming%20Sleep%20Oil.jpg",
  "gut-brain-axis-microbiome-affects-mood": "/attached_assets/remedy_images/Smart%20Lions%20Mane%20Mushroom%20Brain%20Tonic.jpg",
  "nature-therapy-mental-health-benefits-green-spaces": "/attached_assets/remedy_images/Energizing%20Lemon%20Water%20Morning%20Detox.jpg",
  "sleep-mental-health-breaking-vicious-cycle": "/attached_assets/remedy_images/Magnolia%20Bark%20Sleep%20Tea.jpg",
  "social-connection-overlooked-pillar-mental-health": "/attached_assets/remedy_images/Vervain%20Nervous%20Exhaustion%20Formula.jpg",
  "cognitive-behavioral-techniques-everyday-stress": "/attached_assets/remedy_images/Memory%20Booster.jpg",
  "exercise-mental-health-more-effective-antidepressants": "/attached_assets/remedy_images/Arctic%20Energy%20Root.jpg",
  "digital-mental-health-apps-tools-actually-work": "/attached_assets/remedy_images/Sharp%20Mind%20Ginkgo%20Memory%20Enhancer.jpg",
  "gratitude-practice-rewiring-brain-happiness": "/attached_assets/remedy_images/Wood%20Betony%20Relief%20Tea.jpg",
  "burnout-recovery-natural-strategies-restore-energy": "/attached_assets/remedy_images/Asian%20Energy%20Tonic.jpg",
  "natural-anti-aging-skin-health-inside-out": "/attached_assets/remedy_images/Youth%20Activation%20Formula.jpg",
  "acne-diet-foods-clear-trigger-breakouts": "/attached_assets/remedy_images/Pure%20Honey%20Acne%20Treatment%20Mask.jpg",
  "essential-oils-skin-safe-uses-benefits": "/attached_assets/remedy_images/natural-pain-relief-herbal-oil.jpg",
  "hair-health-nutrients-herbs-growth-strength": "/attached_assets/remedy_images/Nourishing%20Rice%20Water%20Hair%20Treatment.jpg",
  "natural-sunscreen-ingredients-protection-without-chemicals": "/attached_assets/remedy_images/Healing%20Aloe%20Burn%20Recovery%20Gel.jpg",
  "dry-skin-remedies-hydration-inside-out": "/attached_assets/remedy_images/Gentle%20Calendula%20Skin%20Soother.jpg",
  "dark-circle-remedies-natural-solutions-tired-eyes": "/attached_assets/remedy_images/Cooling%20Cucumber%20Eye%20Compress.jpg",
  "diy-face-masks-kitchen-ingredients-glowing-skin": "/attached_assets/remedy_images/Fresh%20Tomato%20Antioxidant%20Face%20Mask.jpg",
  "eczema-natural-treatments-soothing-inflammation-naturally": "/attached_assets/remedy_images/Natural%20Oat%20Bath%20Skin%20Soother.jpg",
  "nail-health-signs-deficiency-natural-strengthening": "/attached_assets/remedy_images/Cellular%20Age%20Reversal.jpg",
  "rosacea-natural-management-calming-facial-redness": "/attached_assets/remedy_images/Soothing%20Oatmeal%20Skin%20Mask.jpg",
  "detox-clear-skin-supporting-elimination-pathways": "/attached_assets/remedy_images/Purifying%20Dandelion%20Nettle%20Kidney%20Cleanse.jpg",
};

export const CATEGORY_FALLBACK_IMAGES: Record<string, string> = {
  "wellness": "/attached_assets/remedy_images/Classic%20Turmeric%20Golden%20Milk%20Elixir.jpg",
  "nutrition": "/attached_assets/remedy_images/Apple%20Cider%20Vinegar%20Digestive%20Aid.jpg",
  "science": "/attached_assets/remedy_images/Clinical-Grade%20Calendula%20Wound%20Healing%20Salve.jpg",
  "fitness": "/attached_assets/remedy_images/Female%20Energy%20Tonic.jpg",
  "mental-health": "/attached_assets/remedy_images/German%20Chamomile%20Peaceful%20Sleep%20Tea.jpg",
  "skin-beauty": "/attached_assets/remedy_images/Natural%20Retinol%20Alternative.jpg",
  "herbs-remedies": "/attached_assets/remedy_images/immune-strengthening-herbal-tea.jpg",
  "healthy-foods": "/attached_assets/remedy_images/Household%20Apple%20Cider%20Vinegar%20Digestive%20Tonic.jpg",
};

export function getArticleImage(slug: string, category?: string): string {
  if (ARTICLE_IMAGE_MAP[slug]) {
    return ARTICLE_IMAGE_MAP[slug];
  }
  if (category && CATEGORY_FALLBACK_IMAGES[category]) {
    return CATEGORY_FALLBACK_IMAGES[category];
  }
  return "/attached_assets/remedy_images/Sleepy-Time%20Chamomile%20Tea%20Aid.jpg";
}
